CREATE TABLE IF NOT EXISTS `side_job` (
    `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `name`	TEXT NOT NULL,
    `monthly_income`	INTEGER NOT NULL,
    `work_hours`	INTEGER NOT NULL,
    `skill_id`	INTEGER NOT NULL,
    `difficulty`	INTEGER NOT NULL,
    `category_id`	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS skill (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name TEXT NOT NULL
);